# Generated by Django 3.2.4 on 2021-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='static/img/house')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='static/img/house')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='static/img/house')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='static/img/house')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='static/img/house')),
            ],
        ),
    ]
