# Generated by Django 3.2.4 on 2021-09-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.house')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.house')),
            ],
        ),
    ]
