# Generated by Django 3.2.4 on 2021-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_mainpageinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seoinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='seoinfo',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='seoinfo',
            name='seo_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
    ]
