# Generated by Django 3.2.4 on 2021-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffsPageImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/img/website/tariffs')),
                ('signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='Подпись')),
            ],
        ),
        migrations.CreateModel(
            name='TariffsPageInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
