# Generated by Django 3.2.4 on 2021-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_tariffspageimages_tariffspageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('site', models.CharField(blank=True, max_length=128, null=True, verbose_name='Коммерческий сайт')),
                ('fio', models.CharField(blank=True, max_length=128, null=True, verbose_name='ФИО')),
                ('location', models.CharField(blank=True, max_length=128, null=True, verbose_name='Локация')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='e-mail')),
                ('code_map', models.TextField(blank=True, null=True, verbose_name='Код карты')),
            ],
        ),
    ]
