# Generated by Django 3.2.4 on 2021-09-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_auto_20210929_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffsPageImages',
        ),
        migrations.DeleteModel(
            name='TariffsPageInfo',
        ),
    ]
