# Generated by Django 3.2.4 on 2021-10-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_serviceunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_counter', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.serviceunit')),
            ],
        ),
    ]
