# Generated by Django 3.2.4 on 2021-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_alter_settingservice_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceunit',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
