# Generated by Django 3.2.4 on 2021-10-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_settingserviceistariff_settingtariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingserviceistariff',
            name='unit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.serviceunit'),
        ),
    ]
