# Generated by Django 3.2.4 on 2021-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_alter_settingserviceistariff_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingserviceistariff',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
