# Generated by Django 3.2.4 on 2021-10-11 13:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adminpanel', '0045_settingpaymentitem_settingtransactionpurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_debt', models.BooleanField(blank=True, null=True)),
                ('house', models.ManyToManyField(blank=True, null=True, to='adminpanel.House')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.userstatus')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
