# Generated by Django 3.2.4 on 2021-10-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_apartmentowner_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentowner',
            name='about_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='personal_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='viber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
