# Generated by Django 3.2.4 on 2021-10-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_auto_20211012_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentowner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/apartmentowner'),
        ),
    ]
