# Generated by Django 3.2.4 on 2021-10-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_account_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.statusaccount'),
        ),
    ]
