# Generated by Django 3.2.4 on 2021-10-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0055_auto_20211021_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.flat'),
        ),
    ]
