# Generated by Django 3.2.4 on 2021-10-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0056_alter_account_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='personal_account',
        ),
    ]
