# Generated by Django 3.2.4 on 2021-10-26 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0060_auto_20211026_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
