# Generated by Django 3.2.4 on 2021-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0063_alter_accounttransaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13)),
                ('account_debt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13)),
            ],
        ),
    ]
