# Generated by Django 3.2.4 on 2021-10-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0066_alter_accounttransaction_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('counter_data', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.settingservice')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.flat')),
                ('status', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.statuscounter')),
            ],
        ),
    ]
