# Generated by Django 3.2.4 on 2021-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0067_counterdata_statuscounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterdata',
            name='counter_data',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
