# Generated by Django 3.2.4 on 2021-11-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0070_alter_settingserviceistariff_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_carried', models.BooleanField(default=1)),
                ('date_first', models.DateField(blank=True, null=True)),
                ('date_last', models.DateField(blank=True, null=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.flat')),
                ('status', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.statusinvoice')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.settingtariff')),
            ],
        ),
    ]
