# Generated by Django 3.2.4 on 2021-11-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0073_serviceisinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceisinvoice',
            name='unit_service',
        ),
    ]
