# Generated by Django 3.2.4 on 2021-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_floor_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Кратский текст')),
                ('is_apps', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('slide_1', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
                ('slide_2', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
                ('slide_3', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
