# Generated by Django 3.2.4 on 2021-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_mainpageinfo_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageNearby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/website')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('slide_1', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
                ('slide_2', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
                ('slide_3', models.ImageField(blank=True, null=True, upload_to='static/img/website/slider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('keyworld', models.TextField(verbose_name='Keywords')),
                ('page', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name page for seo information')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
