# Generated by Django 3.2.4 on 2021-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20210924_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageslider',
            name='slide',
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='slide_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/website/slider'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='slide_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/website/slider'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='slide_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/website/slider'),
        ),
    ]
