# Generated by Django 3.2.4 on 2021-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210924_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткий текст'),
        ),
    ]
