# Generated by Django 3.2.4 on 2021-09-24 13:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20210924_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Краткий текст'),
        ),
    ]
