# Generated by Django 3.2.4 on 2021-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_aboutpagedopinfo_aboutpageinfo_photogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDopGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('photo_dop', models.ImageField(blank=True, null=True, upload_to='static/img/website/about')),
            ],
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='refers_to',
        ),
    ]
