# Generated by Django 3.2.4 on 2021-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_auto_20210930_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Коммерческий сайт'),
        ),
    ]
