# Generated by Django 3.2.4 on 2021-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='static/img/website/document'),
        ),
    ]
