# Generated by Django 3.2.4 on 2021-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_auto_20210930_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, default='Пустой документ', max_length=64, null=True),
        ),
    ]
