# Generated by Django 3.2.4 on 2021-10-01 08:25

import adminpanel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='static/img/website/document', validators=[adminpanel.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'pdf'])]),
        ),
    ]
