# Generated by Django 3.2.4 on 2021-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
