# Generated by Django 3.2.4 on 2021-10-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_alter_settingservice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingservice',
            name='unit',
            field=models.ForeignKey(blank=True, default='Выберите...', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.serviceunit'),
        ),
    ]
