# Generated by Django 3.2.4 on 2021-10-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_auto_20211006_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingservice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminpanel.serviceunit'),
        ),
    ]
