# Generated by Django 3.2.4 on 2021-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0054_alter_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='house',
        ),
        migrations.RemoveField(
            model_name='account',
            name='section',
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
