# Generated by Django 3.2.4 on 2021-10-26 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0059_auto_20211026_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
