# Generated by Django 3.2.4 on 2021-10-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0061_alter_accounttransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.settingpaymentitem'),
        ),
    ]
