# Generated by Django 3.2.4 on 2021-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0062_alter_accounttransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
