# Generated by Django 3.2.4 on 2021-10-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0064_cashbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashbox',
        ),
    ]
