# Generated by Django 3.2.4 on 2021-10-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0065_delete_cashbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.account'),
        ),
    ]
