# Generated by Django 3.2.4 on 2021-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0074_remove_serviceisinvoice_unit_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceisinvoice',
            name='currency',
        ),
        migrations.AddField(
            model_name='serviceisinvoice',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
