# Generated by Django 3.2.4 on 2021-12-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0076_masterrequest_statusrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='type_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.typemaster'),
        ),
    ]
