# Generated by Django 3.2.4 on 2021-12-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0077_auto_20211208_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrequest',
            name='type_master',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.typemaster'),
        ),
    ]
