# Generated by Django 3.2.4 on 2021-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0083_remove_account_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='counters_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
