# Generated by Django 3.2.4 on 2022-01-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0087_auto_20211224_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentowner',
            name='status',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.userstatus'),
        ),
    ]
